#42: Add architecture diagrams
exasol/data-science-sandbox pull request #62
Opened 2023-11-16 14:30 UTC by tkilias

2023-11-17 12:59 UTC, ckunki requested changes

2023-11-17 12:59 UTC, ckunki commented on doc/design/exasol_extension_wrappers.drawio.png
for better readability maybe replace individual stereotype labels by a legend explaining for all arrows "A 🠖 B"  to mean "A uses B"

2023-11-17 12:59 UTC, ckunki commented on doc/design/image_building.drawio.png
I think this image could be confusing. 

* There are boxes from different domains:
  * ansible = software component / tool 
  * EC2: AWS service 
  * AMI image: ("physical") artifact 
  * Esp. in "DSS Repo": "Image building" is a functionality while "Notebooks" is a kind of "asset" or "artifact"
* Also the numbers might be confusion
* an observer cannot assign the labels on the left to the arrows as these are overlapping

I propose
* try to minimize domains 
* add a legend
* use a separate style for each domain: color, line, font, fill, corners, ...
* move labels (if possible)

2023-11-17 12:59 UTC, ckunki commented on doc/design/notebook_structure.drawio.png
for better readability maybe replace individual stereotype labels by a legend explaining for all arrows "A 🠖 B"  to mean "A links to B"

2023-11-17 12:59 UTC, ckunki commented on doc/design/notebook_structure.drawio.png
Maybe add a top level heading and a sentence to each diagram, here: 
## Notebook pages planned for DSS 
The DSS is planned to contain a number of Jupiter notebooks. 
Each notebook provides either an overview linking to several related notebooks on the next level or allows the user to perform a specific task like training a specific machine-learning model.

2023-11-17 12:59 UTC, ckunki commented on doc/design/notebook_structure.drawio.png
Maybe add an indicator (icon, asterisk, percentage, ...) to each box to tell its status, e.g. 
* in progress
* planned
* finished

2023-11-17 12:59 UTC, ckunki commented on doc/design/slc_activation.drawio.png
Maybe add a top level heading and a sentence to each diagram, here:
### How to use a custom SLC in Exasol database
Exasol database comes with a default script language container (SLC) allowing database users to execute scripts in a programming language such as Java or Python. 
The following diagram explains the steps to create a custom SLC, containing additional libraries for example.

2023-11-17 12:59 UTC, ckunki commented on doc/design/dependencies.drawio.png
Maybe add a top level heading and a sentence to each diagram, here:

### Components of the Data Science Sandbox (DSS)
DSS contains components maintained in different GitHub repositories. 
The following diagram shows the components and their dependencies.

2023-11-17 12:59 UTC, ckunki commented on doc/design/exasol_extension_wrappers.drawio.png
Maybe add a top level heading and a sentence to each diagram, here:
## Extension Wrappers
The following diagram shows various extension wrappers available in the DSS enabling to use services offered by a cloud component or Exasol database in a convenient way.

2023-11-17 12:59 UTC, ckunki commented on doc/design/image_building.drawio.png
Maybe add a top level heading and a sentence to each diagram, here:
## Image building
DSS repository contains scripts to create _images_ in different formats, such as AMI or Docker Image.
The following diagram shows the steps required to build and publish such images.

2023-11-17 12:59 UTC, ckunki commented on doc/design/image_building.drawio.png
maybe add an arrow and a box for publishing Docker images.

2023-11-17 12:59 UTC, ckunki commented on doc/design/user_flow_sandbox_config.drawio.png
Maybe add a top level heading and a sentence to each diagram, here:
### User flow to configure the Data Science Sandbox (DSS)
DSS support a variety of usage scenarios. 
The following diagram explains the flow for a user to configure the DSS for their favored scenario.

2023-11-17 12:59 UTC, ckunki commented on doc/design/user_flow_sandbox_config.drawio.png
I think this diagram correctly does not use any labels for the vertices, as this should be obvious :+1:

2023-11-17 12:59 UTC, ckunki commented on doc/design/user_flow_sandbox_config.drawio.png
Proposals: 
* Rename Box 1 (on top) to "Create/Open Secure Configuration Storage (SCS) with master password"
* Rename Box 3 to "User adds credentials for Exasol database instance to SCS"
* Rename Box 4 to "Credentials in SCS are successfully updated" 
* Rename Box 5 to "Create or check if database schema exists"
* Rename Box at the bottom to "Table of Contents"

2023-11-17 12:59 UTC, ckunki commented on doc/design/user_flow_starting_dss.drawio.png
Maybe add a top level heading and a sentence to each diagram, here:

## User flow when launching the DSS 
The following diagram explains the flow for a user to launch a Docker Container containing the DSS.

2023-11-17 12:59 UTC, ckunki commented on doc/design/user_flow_starting_dss.drawio.png
Maybe rename the file to `user_flow_starting_dss_docker_container.drawio.png`

2023-11-17 12:59 UTC, ckunki commented on doc/design/user_flow_starting_dss.drawio.png
Comments 
* ip usually is `localhost`, but can be different depending on user's  setup
* add reference to diagram `doc/design/notebook_structure.drawio.png`

2023-11-17 14:34 UTC, tkilias commented on doc/design/notebook_structure.drawio.png
I would not any status information to the diagram, because it is a design document and not for tracking progress. It is simply not the right tool to track progress.

2023-11-20 07:26 UTC, tkilias commented on doc/design/user_flow_starting_dss.drawio.png
I don't understand, what I should do regarding the IP. I could rename it to host, but everything else depends on the user setup and about that I don't care in this diagram.

2023-11-20 14:42 UTC, ckunki approved these changes

2023-11-20 16:17 UTC, merged